server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins : "http://localhost:3000"
            allowed-headers : "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
